// vue-project/src/components/Footer.vue
<template>
  <footer class="">
    <div class="row bg-dark rcs-footer">
      <div class="col-md-12 text-center p-3 text-white">
        <a href="/">
        {{anchorLabel}} <i class="fa fa-copyright"></i>
        </a>
        | {{title}}
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
  data(){
    return {
      title: (new Date).getFullYear(),
      anchorLabel: 'Rcsproductions'

    }
  }
}
</script>

// angular-project/src/app/htmlComponents/html/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent{

  dt = new Date().getFullYear()

}

<footer>
  <div  class="bg-dark">
    <div class="col-md-12 text-center p-3 text-white">
      <a href="/">RCSProductions <i className="fa fa-copyright"></i></a> | {{dt}}
    </div>
  </div>
</footer>
