// vue-project/src/components/Footer.vue
<template>
  <footer class="">
    <div class="row bg-dark rcs-footer">
      <div class="col-md-12 text-center p-3 text-white">
        <a href="/">
        {{anchorLabel}} <i class="fa fa-copyright"></i>
        </a>
        | {{title}}
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
  data(){
    return {
      title: (new Date).getFullYear(),
      anchorLabel: 'Rcsproductions'

    }
  }
}
</script>

// react-project/src/htmlElements/footer.js
import React from 'react'
import { Row,Col } from 'react-bootstrap';

class Footer extends React.Component {
  constructor(props){
    super(props);
    this.state = { year: (new Date()).getFullYear()  };

  }

  render() {
    return (

      		<Row  className="bg-dark">
      			<Col className="col-md-12 text-center p-3 text-white">
      				<a href="/">RCSProductions <i className="fa fa-copyright"></i></a> | {this.state.year}
            </Col>
      		</Row>


    )
  }

}
export default Footer
